import { Bill } from '@/types';

export const mockBills: Bill[] = [
  {
    id: '1',
    title: "Dinner at Tony's",
    description: 'Italian restaurant with the team',
    totalAmount: 120.0,
    bankAccountNumber: '1234567890',
    createdBy: 'user1',
    createdAt: new Date('2024-01-15'),
    dueDate: new Date('2024-01-25'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Margherita Pizza', price: 18.99, quantity: 1, selectedBy: ['user1', 'user2'] },
      { id: 'item2', name: 'Caesar Salad', price: 12.5, quantity: 2, selectedBy: ['user2'] },
      { id: 'item3', name: 'Pasta Carbonara', price: 16.75, quantity: 1, selectedBy: ['user3'] },
      { id: 'item4', name: 'Tiramisu', price: 8.99, quantity: 3, selectedBy: ['user1', 'user2', 'user3'] },
    ],
    bankDetails: {
      bankName: 'Chase Bank',
      accountName: 'John Doe',
      accountNumber: '1234567890',
    },
    status: 'select',
    total: 83.22,
    tag: 'Food & Dining',
  },
  {
    id: '2',
    title: 'Weekend Groceries',
    description: 'Shared groceries for the house',
    totalAmount: 45.5,
    bankAccountNumber: '0987654321',
    createdBy: 'user1',
    createdAt: new Date('2024-01-12'),
    dueDate: new Date('2024-01-20'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user4', name: 'Sarah Wilson', email: 'sarah@example.com' },
    ],
    items: [
      { id: 'item5', name: 'Milk', price: 4.99, quantity: 2, selectedBy: ['user1', 'user4'] },
      { id: 'item6', name: 'Bread', price: 3.5, quantity: 1, selectedBy: ['user1', 'user4'] },
      { id: 'item7', name: 'Eggs', price: 5.99, quantity: 1, selectedBy: ['user1'] },
    ],
    bankDetails: {
      bankName: 'Bank of America',
      accountName: 'John Doe',
      accountNumber: '0987654321',
    },
    status: 'pay',
    total: 14.48,
    tag: 'Groceries',
  },
  {
    id: '3',
    title: 'Movie Night Snacks',
    totalAmount: 25.0,
    bankAccountNumber: '1122334455',
    createdBy: 'user2',
    createdAt: new Date('2024-01-10'),
    dueDate: new Date('2024-01-18'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
    ],
    items: [
      { id: 'item8', name: 'Popcorn', price: 6.99, quantity: 2, selectedBy: ['user1', 'user2'] },
      { id: 'item9', name: 'Soda Pack', price: 8.99, quantity: 1, selectedBy: ['user1', 'user2'] },
    ],
    bankDetails: {
      bankName: 'Wells Fargo',
      accountName: 'Jane Smith',
      accountNumber: '1122334455',
    },
    status: 'closed',
    total: 15.98,
    tag: 'Entertainment',
  },
  {
    id: '4',
    title: 'Office Lunch Order',
    description: 'Team lunch from local deli',
    totalAmount: 85.0,
    bankAccountNumber: '5566778899',
    createdBy: 'user1',
    createdAt: new Date('2024-01-08'),
    dueDate: new Date('2024-01-22'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
      { id: 'user4', name: 'Sarah Wilson', email: 'sarah@example.com' },
    ],
    items: [
      { id: 'item10', name: 'Sandwich Combo', price: 12.99, quantity: 3, selectedBy: ['user1', 'user3', 'user4'] },
      { id: 'item11', name: 'Salad Bowl', price: 9.99, quantity: 2, selectedBy: ['user1', 'user4'] },
    ],
    bankDetails: {
      bankName: 'Chase Bank',
      accountName: 'John Doe',
      accountNumber: '5566778899',
    },
    status: 'select',
    total: 58.95,
    tag: 'Work',
  },
  {
    id: '5',
    title: 'Birthday Party Supplies',
    description: "Decorations and cake for Sarah's birthday",
    totalAmount: 65.0,
    bankAccountNumber: '9988776655',
    createdBy: 'user3',
    createdAt: new Date('2024-01-05'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item12', name: 'Birthday Cake', price: 35.0, quantity: 1, selectedBy: ['user1', 'user2', 'user3'] },
      { id: 'item13', name: 'Decorations', price: 20.0, quantity: 1, selectedBy: ['user2', 'user3'] },
    ],
    bankDetails: {
      bankName: 'Wells Fargo',
      accountName: 'Mike Johnson',
      accountNumber: '9988776655',
    },
    status: 'pay',
    total: 55.0,
    tag: 'Celebration',
  },
]; 