import { Bill } from '@/types';

export const mockBills: Bill[] = [
  {
    id: '1',
    title: "Dinner at Tony's",
    description: 'Italian restaurant with the team',
    totalAmount: 120.0,
    bankAccountNumber: '1234567890',
    createdBy: 'user1',
    createdAt: new Date('2024-01-15'),
    dueDate: new Date('2024-01-25'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Margherita Pizza', price: 18.99, quantity: 1, selectedBy: ['user1', 'user2'] },
      { id: 'item2', name: 'Caesar Salad', price: 12.5, quantity: 2, selectedBy: ['user2'] },
      { id: 'item3', name: 'Pasta Carbonara', price: 16.75, quantity: 1, selectedBy: ['user3'] },
      { id: 'item4', name: 'Tiramisu', price: 8.99, quantity: 3, selectedBy: ['user1', 'user2', 'user3'] },
    ],
    bankDetails: {
      bankName: 'Chase Bank',
      accountName: 'John Doe',
      accountNumber: '1234567890',
    },
    status: 'select',
    total: 83.22,
    tag: 'Food & Dining',
  },
  {
    id: '2',
    title: 'Weekend Groceries',
    description: 'Shared groceries for the house',
    totalAmount: 45.5,
    bankAccountNumber: '0987654321',
    createdBy: 'user1',
    createdAt: new Date('2024-01-12'),
    dueDate: new Date('2024-01-20'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user4', name: 'Sarah Wilson', email: 'sarah@example.com' },
    ],
    items: [
      { id: 'item5', name: 'Milk', price: 4.99, quantity: 2, selectedBy: ['user1', 'user4'] },
      { id: 'item6', name: 'Bread', price: 3.5, quantity: 1, selectedBy: ['user1', 'user4'] },
      { id: 'item7', name: 'Eggs', price: 5.99, quantity: 1, selectedBy: ['user1'] },
    ],
    bankDetails: {
      bankName: 'Bank of America',
      accountName: 'John Doe',
      accountNumber: '0987654321',
    },
    status: 'pay',
    total: 14.48,
    tag: 'Groceries',
  },
  {
    id: '3',
    title: 'Movie Night Snacks',
    totalAmount: 25.0,
    bankAccountNumber: '1122334455',
    createdBy: 'user2',
    createdAt: new Date('2024-01-10'),
    dueDate: new Date('2024-01-18'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
    ],
    items: [
      { id: 'item8', name: 'Popcorn', price: 6.99, quantity: 2, selectedBy: ['user1', 'user2'] },
      { id: 'item9', name: 'Soda Pack', price: 8.99, quantity: 1, selectedBy: ['user1', 'user2'] },
    ],
    bankDetails: {
      bankName: 'Wells Fargo',
      accountName: 'Jane Smith',
      accountNumber: '1122334455',
    },
    status: 'closed',
    total: 15.98,
    tag: 'Entertainment',
  },
  {
    id: '4',
    title: 'Office Lunch Order',
    description: 'Team lunch from local deli',
    totalAmount: 85.0,
    bankAccountNumber: '5566778899',
    createdBy: 'user1',
    createdAt: new Date('2024-01-08'),
    dueDate: new Date('2024-01-22'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
      { id: 'user4', name: 'Sarah Wilson', email: 'sarah@example.com' },
    ],
    items: [
      { id: 'item10', name: 'Sandwich Combo', price: 12.99, quantity: 3, selectedBy: ['user1', 'user3', 'user4'] },
      { id: 'item11', name: 'Salad Bowl', price: 9.99, quantity: 2, selectedBy: ['user1', 'user4'] },
    ],
    bankDetails: {
      bankName: 'Chase Bank',
      accountName: 'John Doe',
      accountNumber: '5566778899',
    },
    status: 'select',
    total: 58.95,
    tag: 'Work',
  },
  {
    id: '5',
    title: 'Birthday Party Supplies',
    description: "Decorations and cake for Sarah's birthday",
    totalAmount: 65.0,
    bankAccountNumber: '9988776655',
    createdBy: 'user3',
    createdAt: new Date('2024-01-05'),
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item12', name: 'Birthday Cake', price: 35.0, quantity: 1, selectedBy: ['user1', 'user2', 'user3'] },
      { id: 'item13', name: 'Decorations', price: 20.0, quantity: 1, selectedBy: ['user2', 'user3'] },
    ],
    bankDetails: {
      bankName: 'Wells Fargo',
      accountName: 'Mike Johnson',
      accountNumber: '9988776655',
    },
    status: 'pay',
    total: 55.0,
    tag: 'Celebration',
  },
  // Host: user1, status: select, some submitted
  {
    id: 'host-select-some',
    title: 'Host Select (Some Submitted)',
    description: 'Host, select status, some members submitted',
    totalAmount: 100,
    bankAccountNumber: '111',
    createdBy: 'user1',
    createdAt: new Date('2024-06-01'),
    status: 'select',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: [] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'John Doe', accountNumber: '111' },
    total: 100,
    tag: 'Test',
  },
  // Host: user1, status: select, all submitted
  {
    id: 'host-select-all',
    title: 'Host Select (All Submitted)',
    description: 'Host, select status, all members submitted',
    totalAmount: 100,
    bankAccountNumber: '112',
    createdBy: 'user1',
    createdAt: new Date('2024-06-02'),
    status: 'select',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: ['user3'] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'John Doe', accountNumber: '112' },
    total: 100,
    tag: 'Test',
    testSubmittedSelections: ['user1', 'user2', 'user3'],
  },
  // Host: user1, status: pay, some paid/unpaid/verified
  {
    id: 'host-pay-mixed',
    title: 'Host Pay (Mixed)',
    description: 'Host, pay status, mixed payment states',
    totalAmount: 100,
    bankAccountNumber: '113',
    createdBy: 'user1',
    createdAt: new Date('2024-06-03'),
    status: 'pay',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: ['user3'] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'John Doe', accountNumber: '113' },
    total: 100,
    tag: 'Test',
    testPaymentStatus: {
      user1: 'unpaid',
      user2: 'paid',
      user3: 'verified',
    },
  },
  // Host: user1, status: pay, all verified
  {
    id: 'host-pay-all-verified',
    title: 'Host Pay (All Verified)',
    description: 'Host, pay status, all payments verified',
    totalAmount: 100,
    bankAccountNumber: '114',
    createdBy: 'user1',
    createdAt: new Date('2024-06-04'),
    status: 'closed',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: ['user3'] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'John Doe', accountNumber: '114' },
    total: 100,
    tag: 'Test',
  },
  // Host: user1, status: closed
  {
    id: 'host-closed',
    title: 'Host Closed',
    description: 'Host, closed status',
    totalAmount: 100,
    bankAccountNumber: '115',
    createdBy: 'user1',
    createdAt: new Date('2024-06-05'),
    status: 'closed',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: ['user3'] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'John Doe', accountNumber: '115' },
    total: 100,
    tag: 'Test',
  },
  // Member: user2, status: select, some submitted
  {
    id: 'member-select-some',
    title: 'Member Select (Some Submitted)',
    description: 'Member, select status, some members submitted',
    totalAmount: 100,
    bankAccountNumber: '211',
    createdBy: 'user3',
    createdAt: new Date('2024-06-06'),
    status: 'select',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: [] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'Mike Johnson', accountNumber: '211' },
    total: 100,
    tag: 'Test',
  },
  // Member: user2, status: select, all submitted
  {
    id: 'member-select-all',
    title: 'Member Select (All Submitted)',
    description: 'Member, select status, all members submitted',
    totalAmount: 100,
    bankAccountNumber: '212',
    createdBy: 'user3',
    createdAt: new Date('2024-06-07'),
    status: 'select',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: ['user3'] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'Mike Johnson', accountNumber: '212' },
    total: 100,
    tag: 'Test',
    testSubmittedSelections: ['user1', 'user2', 'user3'],
  },
  // Member: user2, status: pay, some paid/unpaid/verified
  {
    id: 'member-pay-mixed',
    title: 'Member Pay (Mixed)',
    description: 'Member, pay status, mixed payment states',
    totalAmount: 100,
    bankAccountNumber: '213',
    createdBy: 'user3',
    createdAt: new Date('2024-06-08'),
    status: 'pay',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: ['user3'] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'Mike Johnson', accountNumber: '213' },
    total: 100,
    tag: 'Test',
    testPaymentStatus: {
      user1: 'unpaid',
      user2: 'unpaid',
      user3: 'paid',
    },
  },
  // Member: user2, status: pay, all verified
  {
    id: 'member-pay-all-verified',
    title: 'Member Pay (All Verified)',
    description: 'Member, pay status, all payments verified',
    totalAmount: 100,
    bankAccountNumber: '214',
    createdBy: 'user3',
    createdAt: new Date('2024-06-09'),
    status: 'closed',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: ['user3'] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'Mike Johnson', accountNumber: '214' },
    total: 100,
    tag: 'Test',
  },
  // Member: user2, status: closed
  {
    id: 'member-closed',
    title: 'Member Closed',
    description: 'Member, closed status',
    totalAmount: 100,
    bankAccountNumber: '215',
    createdBy: 'user3',
    createdAt: new Date('2024-06-10'),
    status: 'closed',
    participants: [
      { id: 'user1', name: 'John Doe', email: 'john@example.com' },
      { id: 'user2', name: 'Jane Smith', email: 'jane@example.com' },
      { id: 'user3', name: 'Mike Johnson', email: 'mike@example.com' },
    ],
    items: [
      { id: 'item1', name: 'Pizza', price: 30, quantity: 1, selectedBy: ['user1'] },
      { id: 'item2', name: 'Salad', price: 20, quantity: 1, selectedBy: ['user2'] },
      { id: 'item3', name: 'Drinks', price: 50, quantity: 1, selectedBy: ['user3'] },
    ],
    bankDetails: { bankName: 'Bank', accountName: 'Mike Johnson', accountNumber: '215' },
    total: 100,
    tag: 'Test',
  },
]; 